FROM alpine:3

LABEL author="Fachri Rahman"
LABEL company="Mortal Kombat" website="https://www.mortalkombat.com/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"